# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 03:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('AND', 'Android'), ('IOS', 'iOS'), ('WPH', 'Windows Phone')], default='AND', max_length=3, verbose_name='Platform')),
                ('device_identifier', models.CharField(max_length=64, unique=True, verbose_name='Identifier')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User device',
                'verbose_name_plural': 'User devices',
            },
        ),
    ]
