# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-19 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20160719_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference', models.CharField(choices=[('EC', 'EASTERN'), ('WC', 'WESTERN')], default='EC', max_length=2, verbose_name='Conference')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('arena', models.CharField(max_length=64, verbose_name='Arena')),
                ('foundation', models.DateField(verbose_name='Foundation')),
                ('about_history', models.TextField(verbose_name='About/History')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
    ]
