# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-19 01:54
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='flag',
            field=models.TextField(default=datetime.datetime(2016, 7, 19, 1, 54, 4, 892801, tzinfo=utc), validators=[django.core.validators.URLValidator()], verbose_name='Flag'),
            preserve_default=False,
        ),
    ]
